// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Migrations use the direct (non-pooled) connection when set, since
    // pooled/transaction-mode connections can't run some DDL. Falls back to
    // DATABASE_URL for local setups with a single connection string.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
